export const categories = [
  { value: 'short-dress', label: 'Short Dress' },
  { value: 'long-dress', label: 'Long Dress' },
  { value: 'co-ord-set', label: 'Co-ord Set' },
  { value: '2-pc-set', label: '2Pc Set' },
  { value: '3-pc-set', label: '3Pc Set' },
  { value: 'coats', label: 'Coats' },
  { value: 'jackets', label: 'Jackets' },
  { value: 'bottoms', label: 'Bottoms' },
  { value: 'crop-tops', label: 'Crop Tops' },
  { value: 'inners', label: 'Inners' },
  { value: 'tops', label: 'Tops' },
  { value: 'shirts', label: 'Shirts' },
  { value: 'tunic', label: 'Tunic' },
  { value: 'pant-trouser', label: 'Pant/Trouser' },
  { value: 'skirt', label: 'Skirt' },
  // { categoryId: 'tunic', label: 'Tunic' },
]